version: "3.9"

services:
  broker:
    build: ./broker
    container_name: rust_broker
    ports:
      - "4000:4000"

  consumer:
    build: ./consumer
    container_name: python_consumer
    depends_on:
      - broker
    environment:
      HOST: broker
      PORT: 4000
    volumes:
      - ./consumer/src:/usr/src/consumer/src
