version: "3.9"

services:
  broker:
    build: ./broker
    container_name: rust_broker
    ports:
      - "4000:4000"

  consumer:
    build: ./consumer
    container_name: python_consumer
    env_file:
      - ./.env.local
    depends_on:
      - broker
    environment:
      HOST: broker
      PORT: 4000
      OLLAMA_HOST: http://host.docker.internal:11434/v1
      BYPASS_TOOL_CONSENT: true
    volumes:
      - ./consumer/src:/usr/src/consumer/src
      - ./output:/usr/src/consumer/output      # AI output files
